# Generated by Django 4.2.23 on 2025-06-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=200)),
                ("song_download_link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concert_date",
                    models.DateTimeField(verbose_name="date concert was held"),
                ),
                ("concert_name", models.CharField(max_length=200)),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concertdownloader.band",
                    ),
                ),
                (
                    "songs",
                    models.ManyToManyField(
                        related_name="concerts", to="concertdownloader.song"
                    ),
                ),
            ],
        ),
    ]
