# Generated by Django 4.2.23 on 2025-06-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertdownloader", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="concert_name",
            new_name="internet_archive_identifier",
        ),
        migrations.RenameField(
            model_name="concert",
            old_name="concert_date",
            new_name="publication_date",
        ),
        migrations.RemoveField(
            model_name="concert",
            name="songs",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
