# Generated by Django 4.2.23 on 2025-06-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "concertdownloader",
            "0002_rename_concert_name_concert_internet_archive_identifier_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="flac_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="concert",
            name="mp3_present",
            field=models.BooleanField(default=False),
        ),
    ]
