# Generated by Django 4.2.23 on 2025-06-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concertdownloader", "0003_concert_flac_present_concert_mp3_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concert",
            name="mp3_present",
        ),
    ]
